Repository OpenSlides/openslides-autoupdate-service, pull requests merged in 2021-06, with the labels that each got.

#221 Fixed spelling of organization
  internal/restrict/def.go
  internal/restrict/permission/collection/committee.go
  internal/restrict/permission/collection/user.go
  internal/restrict/permission/collections.go
  internal/restrict/permission/dataprovider/dataprovider.go
  internal/restrict/permission/tests/fields.go
  internal/restrict/permission/tests/testcases/committee/read.yml
  internal/restrict/permission/tests/testcases/organisation/read.yml
  internal/restrict/permission/tests/testcases/organization/read.yml
  internal/restrict/permission/tests/testcases/user/fields_in_one_meeting.yml
Labels: autoupdate

#226 Projector.service projector countdown/message based on agenda item list
  internal/projector/slide/projector.go
  internal/projector/slide/projector_test.go
Labels: autoupdate, go

#224 Projector.service mediafile based on agenda item list
  internal/projector/slide/mediafile.go
  internal/projector/slide/mediafile_test.go
Labels: autoupdate, go

#235 Sort AgendaItemList by weight (Preordered by backend sort)
  internal/projector/slide/agenda.go
  internal/projector/slide/agenda_test.go
Labels: autoupdate, projector

#237 Can manage users
  internal/restrict/def.go
  internal/restrict/permission/collection/committee.go
  internal/restrict/permission/perm/generated.go
  internal/restrict/permission/tests/fields.go
  internal/restrict/permission/tests/testcases/committee/read.yml
Labels: autoupdate

#236 Projector.service: Topic slider
  internal/projector/slide/topic.go
  internal/projector/slide/topic_test.go
Labels: autoupdate, projector
