Repository OpenSlides/openslides-autoupdate-service, pull requests merged in 2023-08, with the labels that each got.

#746 Fix cache.fetchMissing
  pkg/datastore/cache/cache.go
  pkg/datastore/cache/cache_test.go
  pkg/datastore/flow_postgres.go
  pkg/redis/stream.go
Labels: clean up

#748 Update the readme
  README.md
Labels: documentation

#761 Connection count for admin
  internal/autoupdate/autoupdate.go
  internal/http/http.go
  pkg/set/set.go
Labels: feature

#687 Remove all text informations from motion slides when…
  internal/projector/slide/motion.go
  internal/projector/slide/motion_test.go
Labels: clean up
