Repository OpenSlides/openslides-autoupdate-service, pull requests merged in 2024-03, with the labels that each got.

#849 Yaml
  go.mod
  go.sum
  internal/models/models.go
  internal/restrict/perm/generate/main.go
  pkg/datastore/dsmock/yaml_data.go
Labels: dependencies

#872 Add Maybe-Type for non required fields
  internal/autoupdate/autoupdate.go
  internal/restrict/collection/mediafile.go
  internal/restrict/collection/meeting.go
  internal/restrict/collection/motion.go
  internal/restrict/collection/option.go
  internal/restrict/collection/speaker.go
  internal/restrict/collection/user.go
  internal/restrict/collection/vote.go
  internal/restrict/perm/perm.go
  pkg/datastore/dsfetch/fields_generated.go
  pkg/datastore/dsfetch/gen_fields/main.go
  pkg/datastore/dsfetch/gen_fields/value.go.tmpl
  pkg/datastore/dsfetch/maybe.go
  pkg/datastore/dsfetch/maybe_test.go
Labels: enhancement

#890 Change LoS projecion for interposed question
  internal/projector/slide/list_of_speakers.go
  internal/projector/slide/list_of_speakers_test.go
Labels: bug

#833 Long polling fallback
  go.mod
  go.sum
  internal/autoupdate/autoupdate.go
  internal/autoupdate/connection.go
  internal/autoupdate/connection_test.go
  internal/autoupdate/filter.go
  internal/autoupdate/mock_test.go
  internal/http/http.go
  internal/http/http_test.go
Labels: feature
