Repository OpenSlides/openslides-autoupdate-service, pull requests merged in 2024-10, with the labels that each got.

#1040 Check organization/enabled_anonymous
  internal/restrict/collection/group_test.go
  internal/restrict/collection/mediafile_test.go
  internal/restrict/collection/meeting.go
  internal/restrict/collection/meeting_mediafile_test.go
  internal/restrict/collection/meeting_test.go
  internal/restrict/collection/mock_test.go
  internal/restrict/collection/point_of_order_category_test.go
  internal/restrict/collection/tag_test.go
  internal/restrict/collection/user_test.go
  internal/restrict/perm/perm.go
  internal/restrict/restrict_test.go
Labels: enhancement, staging

#1026 New rule for derived motions
  internal/restrict/collection/motion.go
  internal/restrict/collection/motion_state.go
  internal/restrict/collection/motion_state_test.go
  internal/restrict/collection/motion_test.go
Labels: enhancement

#1044 Rename anonymous in public access
  README.md
  environment.md
  internal/http/connection_count.go
  internal/http/interfaces.go
  internal/restrict/collection/group_test.go
  internal/restrict/collection/mediafile_test.go
  internal/restrict/collection/meeting.go
  internal/restrict/collection/meeting_mediafile_test.go
  internal/restrict/collection/meeting_test.go
  internal/restrict/collection/meeting_user_test.go
  internal/restrict/collection/organization.go
  internal/restrict/collection/organization_tag_test.go
  internal/restrict/collection/organization_test.go
  internal/restrict/collection/personal_note_test.go
  internal/restrict/collection/user_test.go
  internal/restrict/perm/perm.go
  main.go
  pkg/auth/auth.go
Labels: clean up

#1050 Add back motion text to projection
  internal/projector/slide/motion.go
  internal/projector/slide/motion_test.go
Labels: bug
